name: Generate Snake

on:
workflow_dispatch:
schedule:
- cron: "0 0 * * *"

jobs:
generate:
runs-on: ubuntu-latest

steps:
  - name: Generate snake
    uses: Platane/snk@v3

    with:
      github_user_name: ameen-alavi
      outputs: dist/github-snake.svg
